/*
 * 인라인 스타일 객체. 정적 CSS(리셋·:focus·:hover·keyframes)와 폰트 <link> 는
 * index.html <head> 에 있다.
 */
const zigzag = (flip) => ({
  height: 14,
  background: `linear-gradient(${flip ? -135 : 135}deg, #FFFFFF 8px, transparent 0), linear-gradient(${flip ? 135 : -135}deg, #FFFFFF 8px, transparent 0)`,
  backgroundSize: "16px 16px",
  backgroundPosition: "left top",
  backgroundColor: "transparent",
});

export const styles = {
    page: { minHeight: "100vh", width: "100%", background: "#EEF1F4", display: "flex", flexDirection: "column", alignItems: "center", padding: "40px 16px", fontFamily: "'Pretendard', -apple-system, sans-serif" },
    receipt: { width: "100%", maxWidth: 440, background: "#FFFFFF", boxShadow: "0 18px 40px rgba(26,29,41,0.12), 0 2px 0 rgba(26,29,41,0.04)", position: "relative" },
    zigzagTop: zigzag(false),
    zigzagBottom: zigzag(true),
    inner: { padding: "8px 30px 34px" },
    header: { textAlign: "center", paddingTop: 22, paddingBottom: 22 },
    logo: { fontSize: 40, color: "#1A1D29", display: "block", margin: "0 auto 12px" },
    title: { fontFamily: "'Pretendard', sans-serif", fontWeight: 800, fontSize: 34, letterSpacing: "-1px", color: "#1A1D29", margin: "0 0 10px" },
    subtitle: { fontSize: 13.5, lineHeight: 1.6, color: "#5C6178", margin: "0 auto", maxWidth: 300 },
    section: { marginTop: 4 },
    sectionLabel: { fontSize: 12, fontWeight: 700, color: "#8A8FA3", letterSpacing: "1px", marginBottom: 12 },
    peopleList: { display: "flex", flexDirection: "column", gap: 6 },
    personRow: { display: "flex", alignItems: "center", gap: 8 },
    nameInputFull: { flex: 1, minWidth: 0, fontFamily: "inherit", fontSize: 15, color: "#1A1D29", background: "transparent", border: "none", borderBottom: "1.5px solid #DDE1E8", padding: "8px 4px" },
    amountWrap: { flex: 1, display: "flex", alignItems: "baseline", justifyContent: "flex-end", borderBottom: "1.5px solid #DDE1E8", padding: "8px 4px", gap: 3 },
    amountInput: { width: "100%", minWidth: 0, textAlign: "right", fontFamily: "'Space Grotesk', 'Pretendard', sans-serif", fontVariantNumeric: "tabular-nums", fontSize: 15, color: "#1A1D29", background: "transparent", border: "none" },
    wonSuffix: { fontSize: 12.5, color: "#8A8FA3", flexShrink: 0 },
    removeBtn: { width: 24, height: 24, flexShrink: 0, border: "none", background: "transparent", color: "#E8503A", fontSize: 13, opacity: 0.45, cursor: "pointer" },
    addBtn: { marginTop: 14, width: "100%", padding: "10px 0", border: "1.5px dashed #C7CCD8", borderRadius: 4, background: "transparent", color: "#4B5165", fontFamily: "inherit", fontSize: 13.5, fontWeight: 500, cursor: "pointer", transition: "background 0.15s, color 0.15s, border-color 0.15s" },
    dashedDivider: { borderTop: "1.5px dashed #DDE1E8", margin: "26px 0" },

    roundsList: { display: "flex", flexDirection: "column", gap: 12 },
    roundCard: { background: "#F6F8FB", border: "1px solid #E3E6EC", borderRadius: 4, padding: 14 },
    roundTopRow: { display: "flex", alignItems: "center", gap: 8, marginBottom: 10 },
    roundTitleInput: { flex: 1, minWidth: 0, fontFamily: "inherit", fontSize: 14, fontWeight: 700, color: "#1A1D29", background: "transparent", border: "none", borderBottom: "1.5px solid #DDE1E8", padding: "6px 2px" },
    roundFieldRow: { display: "flex", gap: 8, marginBottom: 10 },
    selectInput: { flex: 1, minWidth: 0, fontFamily: "inherit", fontSize: 13.5, color: "#1A1D29", background: "#FFFFFF", border: "1px solid #DDE1E8", borderRadius: 4, padding: "8px 6px" },
    selectInputWarn: { borderColor: "#E8503A", color: "#9AA0B0" },
    payerWarn: { margin: "-2px 0 10px", fontSize: 11.5, fontWeight: 500, color: "#E8503A" },
    roundChipHeadRow: { display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: 6 },
    roundChipLabel: { fontSize: 11.5, color: "#8A8FA3", fontWeight: 500 },
    roundToggleAllBtn: { border: "none", background: "transparent", color: "#5C6178", fontSize: 11.5, fontWeight: 500, cursor: "pointer", textDecoration: "underline" },
    chipRow: { display: "flex", flexWrap: "wrap", gap: 6 },
    chip: { fontFamily: "inherit", fontSize: 12.5, padding: "6px 10px", border: "1px solid", cursor: "pointer", borderRadius: 4, transition: "background 0.12s, color 0.12s, border-color 0.12s" },
    chipActive: { background: "#E6F7EF", borderColor: "#0F9D64", color: "#0C6B4E", fontWeight: 700 },
    chipInactive: { background: "#FFFFFF", borderColor: "#DDE1E8", color: "#9AA0B0" },
    chipEmptyHint: { fontSize: 12, color: "#9AA0B0" },

    summaryBlock: { display: "flex", flexDirection: "column", gap: 10 },
    summaryRow: { display: "flex", justifyContent: "space-between", alignItems: "baseline" },
    summaryLabel: { fontSize: 13.5, color: "#4B5165" },
    summaryValue: { fontFamily: "'Space Grotesk', 'Pretendard', sans-serif", fontSize: 16, fontWeight: 700, color: "#1A1D29", fontVariantNumeric: "tabular-nums" },
    calcBtn: { marginTop: 26, width: "100%", padding: "15px 0", border: "none", borderRadius: 4, background: "#E8503A", color: "#FFFFFF", fontFamily: "inherit", fontSize: 15.5, fontWeight: 700, letterSpacing: "0.5px", boxShadow: "2px 3px 0 #B8391F", transition: "transform 0.12s, box-shadow 0.12s" },
    hint: { marginTop: 10, fontSize: 12, color: "#9AA0B0", textAlign: "center" },

    captureWrap: { background: "#FFFFFF", padding: "28px 24px 26px" },
    captureTitleRow: { display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: 2, paddingTop: 4, paddingRight: 4 },
    captureTitleText: { fontFamily: "'Pretendard', sans-serif", fontWeight: 800, fontSize: 20, letterSpacing: "-0.3px", color: "#1A1D29", display: "inline-flex", alignItems: "center", gap: 6 },
    captureLogo: { fontSize: 22, color: "#1A1D29" },
    captureDate: { fontSize: 11.5, color: "#9AA0B0", margin: "2px 0 18px" },
    statsBlock: { marginBottom: 4 },
    statsSubLabel: { fontSize: 12, fontWeight: 700, color: "#8A8FA3", letterSpacing: "0.5px", marginBottom: 8 },
    statsHeadRow: { display: "flex", gap: 6, padding: "0 2px 6px", borderBottom: "1px solid #E3E6EC" },
    statsCell: { fontSize: 11, color: "#9AA0B0", fontWeight: 500 },
    statsRow: { display: "flex", gap: 6, padding: "8px 2px", borderBottom: "1px solid #F0F2F6" },
    statsName: { fontSize: 13.5, fontWeight: 700, color: "#1A1D29" },
    statsNum: { fontFamily: "'Space Grotesk', 'Pretendard', sans-serif", fontSize: 13, color: "#1A1D29", textAlign: "right", fontVariantNumeric: "tabular-nums" },

    stamp: { fontFamily: "'Space Grotesk', 'Pretendard', sans-serif", fontVariantNumeric: "tabular-nums", fontSize: 12, fontWeight: 700, color: "#0F9D64", border: "2px solid #0F9D64", borderRadius: 4, padding: "3px 8px", letterSpacing: "1px", transform: "rotate(-8deg)", display: "inline-block", animation: "stampIn 0.4s ease-out" },
    evenText: { fontSize: 14, color: "#4B5165", textAlign: "center", padding: "10px 0" },
    groupHint: { fontSize: 12, color: "#9AA0B0", margin: "0 0 14px" },
    groupList: { display: "flex", flexDirection: "column", gap: 10 },
    groupCard: { background: "#F6F8FB", border: "1px solid #E3E6EC", borderRadius: 4, padding: "12px 14px" },
    groupHeadRow: { display: "flex", justifyContent: "space-between", alignItems: "baseline", marginBottom: 8, paddingBottom: 8, borderBottom: "1px solid #E3E6EC" },
    groupFrom: { fontSize: 15.5, fontWeight: 700, color: "#1A1D29" },
    groupSubtotal: { fontFamily: "'Space Grotesk', 'Pretendard', sans-serif", fontVariantNumeric: "tabular-nums", fontSize: 12.5, fontWeight: 700, color: "#E8503A" },
    txList: { listStyle: "none", margin: 0, padding: 0, display: "flex", flexDirection: "column", gap: 5 },
    txRow: { display: "flex", alignItems: "baseline", gap: 8 },
    txArrow: { fontSize: 13, color: "#B9BFCC" },
    txTo: { fontSize: 14.5, fontWeight: 700, color: "#1A1D29", flex: 1 },
    txAmount: { fontFamily: "'Space Grotesk', 'Pretendard', sans-serif", fontSize: 15, fontWeight: 700, color: "#0F9D64", fontVariantNumeric: "tabular-nums" },

    actionRow: { display: "flex", gap: 8, marginTop: 16 },
    copyBtn: { flex: 1, padding: "12px 0", border: "none", borderRadius: 4, background: "#0F9D64", color: "#FFFFFF", fontFamily: "inherit", fontSize: 14, fontWeight: 700, cursor: "pointer", transition: "background 0.15s" },
    downloadBtn: { flex: 1, padding: "12px 0", border: "none", borderRadius: 4, background: "#1A1D29", color: "#FFFFFF", fontFamily: "inherit", fontSize: 14, fontWeight: 700, transition: "background 0.15s" },

    footer: { marginTop: 20, display: "flex", alignItems: "center", gap: 8, fontSize: 12, color: "#9AA0B0" },
    footerLink: { color: "#9AA0B0", textDecoration: "none" },
    footerDot: { color: "#C7CCD8" },

    previewOverlay: { position: "fixed", inset: 0, zIndex: 1000, background: "rgba(20,22,30,0.82)", display: "flex", flexDirection: "column", alignItems: "center", justifyContent: "center", padding: 20, overflowY: "auto" },
    previewBox: { width: "100%", maxWidth: 380, display: "flex", flexDirection: "column", alignItems: "center", gap: 12 },
    previewHint: { margin: 0, color: "#FFFFFF", fontSize: 13.5, lineHeight: 1.6, textAlign: "center" },
    previewImg: { width: "100%", height: "auto", borderRadius: 6, boxShadow: "0 12px 32px rgba(0,0,0,0.4)", background: "#FFFFFF", WebkitTouchCallout: "default" },
    previewBtnRow: { display: "flex", gap: 8, width: "100%" },
    previewShareBtn: { flex: 1, padding: "12px 0", border: "none", borderRadius: 4, background: "#0F9D64", color: "#FFFFFF", fontFamily: "inherit", fontSize: 14, fontWeight: 700, cursor: "pointer" },
    previewCloseBtn: { flex: 1, padding: "12px 0", border: "1px solid rgba(255,255,255,0.5)", borderRadius: 4, background: "transparent", color: "#FFFFFF", fontFamily: "inherit", fontSize: 14, fontWeight: 700, cursor: "pointer" },
};
