/*
 * 인라인 스타일 객체. 정적 CSS(리셋·:focus·:hover·keyframes)와 폰트 <link> 는
 * index.html <head> 에 있다.
 */

// ── 브랜드 색상 ─────────────────────────────
export const C_RED   = "#E8503A";  // 강조·경고·브랜드
export const C_DARK  = "#1A1D29";  // 기본 텍스트·배경
export const C_WHITE = "#FFFFFF";  // 반전 텍스트·배경
export const C_MUTED = "#9AA0B0";  // 비활성·보조 텍스트
export const C_GREEN = "#0F9D64";  // 성공·양수
export const C_SUB   = "#5C6178";  // 보조 텍스트·설명
export const C_BG    = "#EEF1F4";  // 페이지 배경 연회색
export const C_DIM   = "#4B5165";  // 설명 텍스트 진회색

const zigzag = (flip) => ({
  height: 14,
  background: `linear-gradient(${flip ? -135 : 135}deg, ${C_WHITE} 8px, transparent 0), linear-gradient(${flip ? 135 : -135}deg, ${C_WHITE} 8px, transparent 0)`,
  backgroundSize: "16px 16px",
  backgroundPosition: "left top",
  backgroundColor: "transparent",
});

// 하단 탭바 높이 (safe-area 제외). page 의 아래 여백이 이 값을 따라간다.
const TAB_BAR_HEIGHT = 58;

export const styles = {
    page: { minHeight: "100vh", width: "100%", background: C_BG, display: "flex", flexDirection: "column", alignItems: "center", padding: `40px 16px calc(${TAB_BAR_HEIGHT + 32}px + env(safe-area-inset-bottom))`, fontFamily: "'Pretendard', -apple-system, sans-serif" },
    receipt: { width: "100%", maxWidth: 440, background: C_WHITE, boxShadow: "0 18px 40px rgba(26,29,41,0.12), 0 2px 0 rgba(26,29,41,0.04)", position: "relative" },
    zigzagTop: zigzag(false),
    zigzagBottom: zigzag(true),
    inner: { padding: "8px 30px 34px" },
    header: { textAlign: "center", paddingTop: 22, paddingBottom: 22 },
    logo: { fontSize: 40, color: C_DARK, display: "block", margin: "0 auto 12px" },
    title: { fontFamily: "'Pretendard', sans-serif", fontWeight: 800, fontSize: 34, letterSpacing: "-1px", color: C_DARK, margin: "0 0 10px" },
    subtitle: { fontSize: 13.5, lineHeight: 1.6, color: C_SUB, margin: "0 auto", maxWidth: 300 },
    section: { marginTop: 4 },
    sectionLabel: { fontSize: 12, fontWeight: 700, color: "#8A8FA3", letterSpacing: "1px", marginBottom: 12 },
    peopleList: { display: "flex", flexDirection: "column", gap: 10 },
    personBlock: { display: "flex", flexDirection: "column", gap: 6 },
    personRow: { display: "flex", alignItems: "center", gap: 8 },
    nameInputFull: { flex: 1, minWidth: 0, fontFamily: "inherit", fontSize: 15, color: C_DARK, background: "transparent", border: "none", borderBottom: "1.5px solid #DDE1E8", padding: "8px 4px" },
    accountToggleBtn: { flexShrink: 0, border: "none", background: "transparent", color: C_SUB, fontSize: 11.5, fontWeight: 600, cursor: "pointer", textDecoration: "underline", padding: "0 2px", whiteSpace: "nowrap" },
    accountInput: { width: "100%", fontFamily: "inherit", fontSize: 13, color: C_DARK, background: "#F6F8FB", border: "1px solid #DDE1E8", borderRadius: 4, padding: "8px 10px" },
    amountWrap: { flex: 1, display: "flex", alignItems: "baseline", justifyContent: "flex-end", borderBottom: "1.5px solid #DDE1E8", padding: "8px 4px", gap: 3 },
    amountInput: { width: "100%", minWidth: 0, textAlign: "right", fontFamily: "'Space Grotesk', 'Pretendard', sans-serif", fontVariantNumeric: "tabular-nums", fontSize: 15, color: C_DARK, background: "transparent", border: "none" },
    wonSuffix: { fontSize: 12.5, color: "#8A8FA3", flexShrink: 0 },
    removeBtn: { width: 24, height: 24, flexShrink: 0, border: "none", background: "transparent", color: C_RED, fontSize: 13, opacity: 0.45, cursor: "pointer" },
    nameWarn: { margin: "-2px 0 0", fontSize: 11.5, fontWeight: 500, color: C_RED },
    addBtn: { marginTop: 14, width: "100%", padding: "10px 0", border: "1.5px dashed #C7CCD8", borderRadius: 4, background: "transparent", color: C_DIM, fontFamily: "inherit", fontSize: 13.5, fontWeight: 500, cursor: "pointer", transition: "background 0.15s, color 0.15s, border-color 0.15s" },
    dashedDivider: { borderTop: "1.5px dashed #DDE1E8", margin: "26px 0" },

    roundsList: { display: "flex", flexDirection: "column", gap: 12 },
    roundCard: { background: "#F6F8FB", border: "1px solid #E3E6EC", borderRadius: 4, padding: 14 },
    roundTopRow: { display: "flex", alignItems: "center", gap: 8, marginBottom: 10 },
    roundTitleInput: { flex: 1, minWidth: 0, fontFamily: "inherit", fontSize: 14, fontWeight: 700, color: C_DARK, background: "transparent", border: "none", borderBottom: "1.5px solid #DDE1E8", padding: "6px 2px" },
    roundFieldRow: { display: "flex", gap: 8, marginBottom: 10 },
    selectInput: { flex: 1, minWidth: 0, fontFamily: "inherit", fontSize: 13.5, color: C_DARK, background: C_WHITE, border: "1px solid #DDE1E8", borderRadius: 4, padding: "8px 6px" },
    selectInputWarn: { borderColor: C_RED, color: C_MUTED },
    payerWarn: { margin: "-2px 0 10px", fontSize: 11.5, fontWeight: 500, color: C_RED },
    roundChipHeadRow: { display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: 6 },
    roundChipLabel: { fontSize: 11.5, color: "#8A8FA3", fontWeight: 500 },
    roundToggleAllBtn: { border: "none", background: "transparent", color: C_SUB, fontSize: 11.5, fontWeight: 500, cursor: "pointer", textDecoration: "underline" },
    chipRow: { display: "flex", flexWrap: "wrap", gap: 6 },
    chip: { fontFamily: "inherit", fontSize: 12.5, padding: "6px 10px", border: "1px solid", cursor: "pointer", borderRadius: 4, transition: "background 0.12s, color 0.12s, border-color 0.12s" },
    chipActive: { background: "#E6F7EF", borderColor: C_GREEN, color: "#0C6B4E", fontWeight: 700 },
    chipInactive: { background: C_WHITE, borderColor: "#DDE1E8", color: C_MUTED },
    chipEmptyHint: { fontSize: 12, color: C_MUTED },

    summaryBlock: { display: "flex", flexDirection: "column", gap: 10 },
    summaryRow: { display: "flex", justifyContent: "space-between", alignItems: "baseline" },
    summaryLabel: { fontSize: 13.5, color: C_DIM },
    summaryValue: { fontFamily: "'Space Grotesk', 'Pretendard', sans-serif", fontSize: 16, fontWeight: 700, color: C_DARK, fontVariantNumeric: "tabular-nums" },
    calcBtn: { marginTop: 26, width: "100%", padding: "15px 0", border: "none", borderRadius: 4, background: C_RED, color: C_WHITE, fontFamily: "inherit", fontSize: 15.5, fontWeight: 700, letterSpacing: "0.5px", boxShadow: "2px 3px 0 #B8391F", transition: "transform 0.12s, box-shadow 0.12s" },
    hint: { marginTop: 10, fontSize: 12, color: C_MUTED, textAlign: "center" },

    captureWrap: { background: C_WHITE, padding: "28px 24px 26px" },
    captureTitleRow: { display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: 2, paddingTop: 4, paddingRight: 4 },
    captureTitleText: { fontFamily: "'Pretendard', sans-serif", fontWeight: 800, fontSize: 20, letterSpacing: "-0.3px", color: C_DARK, display: "inline-flex", alignItems: "center", gap: 6 },
    captureLogo: { fontSize: 22, color: C_DARK },
    captureDate: { fontSize: 11.5, color: C_MUTED, margin: "2px 0 18px" },
    statsBlock: { marginBottom: 4 },
    statsSubLabel: { fontSize: 12, fontWeight: 700, color: "#8A8FA3", letterSpacing: "0.5px", marginBottom: 8 },
    statsHeadRow: { display: "flex", gap: 6, padding: "0 2px 6px", borderBottom: "1px solid #E3E6EC" },
    statsCell: { fontSize: 11, color: C_MUTED, fontWeight: 500 },
    statsRow: { display: "flex", gap: 6, padding: "8px 2px", borderBottom: "1px solid #F0F2F6" },
    statsName: { fontSize: 13.5, fontWeight: 700, color: C_DARK },
    statsNum: { fontFamily: "'Space Grotesk', 'Pretendard', sans-serif", fontSize: 13, color: C_DARK, textAlign: "right", fontVariantNumeric: "tabular-nums" },

    stamp: { fontFamily: "'Space Grotesk', 'Pretendard', sans-serif", fontVariantNumeric: "tabular-nums", fontSize: 12, fontWeight: 700, color: C_GREEN, border: `2px solid ${C_GREEN}`, borderRadius: 4, padding: "3px 8px", letterSpacing: "1px", transform: "rotate(-8deg)", display: "inline-block", animation: "stampIn 0.4s ease-out" },
    evenText: { fontSize: 14, color: C_DIM, textAlign: "center", padding: "10px 0" },
    groupHint: { fontSize: 12, color: C_MUTED, margin: "0 0 14px" },
    groupList: { display: "flex", flexDirection: "column", gap: 10 },
    groupCard: { background: "#F6F8FB", border: "1px solid #E3E6EC", borderRadius: 4, padding: "12px 14px" },
    groupHeadRow: { display: "flex", justifyContent: "space-between", alignItems: "baseline", marginBottom: 8, paddingBottom: 8, borderBottom: "1px solid #E3E6EC" },
    groupFrom: { fontSize: 15.5, fontWeight: 700, color: C_DARK },
    groupSubtotal: { fontFamily: "'Space Grotesk', 'Pretendard', sans-serif", fontVariantNumeric: "tabular-nums", fontSize: 12.5, fontWeight: 700, color: C_RED },
    txList: { listStyle: "none", margin: 0, padding: 0, display: "flex", flexDirection: "column", gap: 8 },
    txItem: {},
    txRow: { display: "flex", alignItems: "baseline", gap: 8 },
    txArrow: { fontSize: 13, color: "#B9BFCC" },
    txTo: { fontSize: 14.5, fontWeight: 700, color: C_DARK, flex: 1 },
    txAccount: { fontSize: 11.5, color: "#8A8FA3", marginLeft: 21, marginTop: 2 },
    txAmount: { fontFamily: "'Space Grotesk', 'Pretendard', sans-serif", fontSize: 15, fontWeight: 700, color: C_GREEN, fontVariantNumeric: "tabular-nums" },

    actionRow: { display: "flex", gap: 8, marginTop: 16 },
    copyBtn: { flex: 1, padding: "12px 0", border: "none", borderRadius: 4, background: C_GREEN, color: C_WHITE, fontFamily: "inherit", fontSize: 14, fontWeight: 700, cursor: "pointer", transition: "background 0.15s" },
    downloadBtn: { flex: 1, padding: "12px 0", border: "none", borderRadius: 4, background: C_DARK, color: C_WHITE, fontFamily: "inherit", fontSize: 14, fontWeight: 700, transition: "background 0.15s" },

    footerWrap: { marginTop: 20, display: "flex", flexDirection: "column", alignItems: "center", gap: 7 },
    footer: { display: "flex", flexWrap: "wrap", justifyContent: "center", alignItems: "center", gap: "4px 8px", maxWidth: 360, fontSize: 12, color: C_MUTED },
    footerLink: { color: C_MUTED, textDecoration: "none" },
    footerGuides: { display: "flex", gap: 8, justifyContent: "center", flexWrap: "wrap" },
    footerGuide: { padding: "6px 12px", border: "1px solid #D5D9E2", borderRadius: 4, background: C_WHITE, color: C_SUB, fontSize: 12.5, fontWeight: 600, textDecoration: "none", transition: "border-color 0.15s, color 0.15s" },
    footerDot: { color: "#C7CCD8" },
    footerLab: { fontSize: 10.5, color: "#CDD1DA", textDecoration: "none", letterSpacing: "0.2px" },

    // 오늘 뭐먹지
    foodField: { marginBottom: 20 },
    foodLabelRow: { display: "flex", alignItems: "baseline", gap: 8, marginBottom: 10 },
    sectionLabelInline: { fontSize: 12, fontWeight: 700, color: "#8A8FA3", letterSpacing: "1px" },
    foodHint: { fontSize: 11.5, color: C_MUTED, margin: "8px 0 0", textAlign: "center" },
    stepper: { display: "flex", alignItems: "center", gap: 14 },
    stepBtn: { width: 40, height: 40, border: "1.5px solid #DDE1E8", borderRadius: 4, background: C_WHITE, color: C_DARK, fontFamily: "inherit", fontSize: 20, lineHeight: 1, cursor: "pointer", transition: "border-color 0.15s" },
    stepValue: { minWidth: 56, textAlign: "center", fontFamily: "'Space Grotesk', 'Pretendard', sans-serif", fontVariantNumeric: "tabular-nums", fontSize: 22, fontWeight: 700, color: C_DARK, display: "inline-flex", alignItems: "baseline", justifyContent: "center", gap: 3 },
    foodEmpty: { fontSize: 13.5, color: C_DIM, textAlign: "center", padding: "18px 8px", background: "#F6F8FB", border: "1px solid #E3E6EC", borderRadius: 4, lineHeight: 1.6 },
    relaxNote: { fontSize: 12, color: "#B8391F", background: "#FDF0EC", borderRadius: 4, padding: "8px 10px", margin: "0 0 12px", lineHeight: 1.5 },
    foodCard: { background: "#F6F8FB", border: "1px solid #E3E6EC", borderRadius: 4, padding: "20px 16px 16px", textAlign: "center" },
    foodPickLabel: { display: "inline-block", fontSize: 11.5, fontWeight: 700, letterSpacing: "1px", color: C_GREEN, border: `1.5px solid ${C_GREEN}`, borderRadius: 4, padding: "2px 8px", transform: "rotate(-4deg)", animation: "stampIn 0.4s ease-out" },
    foodEmoji: { fontSize: 56, lineHeight: 1.1, margin: "12px 0 4px" },
    foodName: { fontSize: 26, fontWeight: 800, letterSpacing: "-0.5px", color: C_DARK },
    foodMeta: { fontSize: 12.5, color: "#8A8FA3", marginTop: 4 },
    pairBox: { margin: "14px auto 2px", padding: "10px 12px", maxWidth: 300, border: "1px dashed #D5D9E2", borderRadius: 4, background: "#FAFBFC" },
    pairLabel: { fontSize: 11.5, fontWeight: 700, color: C_MUTED },
    pairName: { marginTop: 2, fontSize: 17, fontWeight: 800, color: C_DARK },
    mapBtn: { flex: 1, display: "flex", alignItems: "center", justifyContent: "center", padding: "12px 0", borderRadius: 4, background: C_DARK, color: C_WHITE, fontSize: 13.5, fontWeight: 700, textDecoration: "none", transition: "background 0.15s" },
    altBlock: { marginTop: 16, display: "flex", flexDirection: "column", gap: 8 },
    altChip: { color: C_DARK, fontSize: 13.5, padding: "8px 12px" },
    rerollBtn: { flex: 1, margin: 0, padding: "11px 0", border: "1.5px dashed #C7CCD8", borderRadius: 4, background: "transparent", color: C_DIM, fontFamily: "inherit", fontSize: 13.5, fontWeight: 600, cursor: "pointer", transition: "background 0.15s, color 0.15s, border-color 0.15s" },
    // 뭐먹지 — 못 먹는 메뉴 직접 입력
    blockedInputRow: { display: "flex", gap: 8, marginTop: 10, alignItems: "center" },
    blockedRow: { display: "flex", flexWrap: "wrap", gap: 6, marginTop: 8 },
    blockedChip: { display: "inline-flex", alignItems: "center", border: "1px solid #F4C4B7", borderRadius: 4, background: "#FDF0EC", color: "#B8391F", fontSize: 12.5, fontWeight: 700, overflow: "hidden" },
    blockedChipNone: { borderColor: "#E3E6EC", background: "#F6F8FB", color: C_MUTED },
    blockedChipToggle: { display: "inline-flex", alignItems: "center", gap: 4, padding: "5px 4px 5px 9px", border: "none", background: "none", color: "inherit", fontFamily: "inherit", fontSize: "inherit", fontWeight: "inherit", cursor: "pointer" },
    blockedChipCount: { fontWeight: 500, opacity: 0.8 },
    blockedChipChevron: { fontSize: 13, flexShrink: 0 },
    blockedChipX: { padding: "5px 9px 5px 6px", border: "none", background: "none", color: "inherit", fontFamily: "inherit", fontSize: 13, lineHeight: 1, cursor: "pointer" },
    blockedList: { listStyle: "none", margin: "8px 0 0", padding: "4px 0", border: "1px solid #E3E6EC", borderRadius: 4, background: "#FAFBFC", maxHeight: 220, overflowY: "auto" },
    blockedItem: { display: "flex", alignItems: "center", gap: 8, padding: "5px 8px 5px 12px", fontSize: 13, color: C_DARK },
    blockedItemOff: { color: C_MUTED, textDecoration: "line-through" },
    blockedItemName: { flex: 1, minWidth: 0 },
    blockedItemGenre: { fontSize: 11, color: C_MUTED },
    blockedItemBtn: { width: 28, height: 28, flexShrink: 0, border: "1px solid #DDE1E8", borderRadius: 4, background: C_WHITE, color: C_DARK, fontFamily: "inherit", fontSize: 16, lineHeight: 1, cursor: "pointer" },
    // 뭐먹지 — 음식 전체 목록
    foodListHead: { display: "flex", alignItems: "center", marginBottom: 16 },
    foodListBack: { width: 48, padding: "4px 0", border: "none", background: "none", color: C_MUTED, fontFamily: "inherit", fontSize: 13, textAlign: "left", cursor: "pointer" },
    foodListTitle: { flex: 1, textAlign: "center", fontSize: 16, fontWeight: 800, color: C_DARK, letterSpacing: "-0.3px" },
    foodListTabs: { display: "flex", gap: 6, overflowX: "auto", paddingBottom: 6, marginBottom: 10, WebkitOverflowScrolling: "touch", scrollbarWidth: "none" },
    foodListTab: { flexShrink: 0, padding: "6px 14px", border: "1.5px solid #DDE1E8", borderRadius: 20, background: C_WHITE, color: C_SUB, fontFamily: "inherit", fontSize: 13, fontWeight: 500, cursor: "pointer", transition: "background 0.12s, color 0.12s" },
    foodListTabOn: { border: "1.5px solid transparent", background: C_RED, color: C_WHITE, fontWeight: 700 },
    foodListCount: { margin: "0 0 10px", fontSize: 12, color: C_MUTED, textAlign: "right" },
    foodListGrid: { display: "grid", gridTemplateColumns: "repeat(3, 1fr)", gap: 8 },
    foodListCard: { display: "flex", flexDirection: "column", alignItems: "center", gap: 3, padding: "10px 6px 8px", background: C_WHITE, border: "1px solid #EEF1F4", borderRadius: 4, textAlign: "center" },
    foodListEmoji: { fontSize: 22, lineHeight: 1 },
    foodListName: { fontSize: 12, fontWeight: 600, color: C_DARK, lineHeight: 1.3, wordBreak: "keep-all" },
    foodListPrice: { fontSize: 10.5, color: C_MUTED },
    foodListRequest: { marginTop: 24, padding: 16, background: "#F6F8FB", borderRadius: 4, textAlign: "center" },
    foodListRequestText: { margin: "0 0 10px", fontSize: 13, color: C_SUB, lineHeight: 1.6 },
    foodListRequestLink: { display: "inline-block", fontSize: 13, fontWeight: 700, color: C_RED, textDecoration: "none" },
    coupangDisclosure: { margin: "6px 0 0", fontSize: 10, color: C_MUTED, lineHeight: 1.5 },

    // 미니게임 — 목록
    addPlayerRow: { display: "flex", gap: 8, marginTop: 12, alignItems: "center" },
    addPlayerBtn: { flexShrink: 0, padding: "9px 16px", border: "none", borderRadius: 4, background: C_DARK, color: C_WHITE, fontFamily: "inherit", fontSize: 13.5, fontWeight: 700, cursor: "pointer", transition: "background 0.15s" },
    gameGrid: { display: "grid", gridTemplateColumns: "1fr 1fr", gap: 10 },
    gameCard: { display: "flex", flexDirection: "column", alignItems: "flex-start", gap: 4, padding: "14px 12px", background: "#F6F8FB", border: "1px solid #E3E6EC", borderRadius: 4, fontFamily: "inherit", textAlign: "left", cursor: "pointer", transition: "border-color 0.15s, transform 0.12s" },
    gameCardLocked: { background: C_WHITE, borderStyle: "dashed", opacity: 0.7 },
    gameCardEmoji: { fontSize: 28, lineHeight: 1.1 },
    gameCardName: { fontSize: 14.5, fontWeight: 800, color: C_DARK },
    gameCardDesc: { fontSize: 11.5, color: "#8A8FA3", lineHeight: 1.45 },
    gameNotice: { marginTop: 12, fontSize: 12.5, fontWeight: 600, color: "#B8391F", background: "#FDF0EC", borderRadius: 4, padding: "8px 10px", textAlign: "center" },

    // 미니게임 — 플레이
    gameTopRow: { display: "flex", justifyContent: "space-between", alignItems: "center", paddingTop: 14 },
    backLink: { fontSize: 13, fontWeight: 600, color: C_SUB, textDecoration: "none", padding: "6px 0" },
    soundHint: { display: "block", width: "100%", margin: "4px 0 10px", padding: "10px 12px", border: `1px dashed ${C_RED}`, borderRadius: 4, background: "#FFF5F2", color: "#C23E2A", fontFamily: "inherit", fontSize: 13, fontWeight: 700, cursor: "pointer" },
    soundBtn: { border: "1px solid #DDE1E8", borderRadius: 4, background: C_WHITE, color: C_SUB, fontFamily: "inherit", fontSize: 12, fontWeight: 600, padding: "6px 10px", cursor: "pointer" },
    gameHeader: { textAlign: "center", padding: "10px 0 16px" },
    gameHeaderEmoji: { fontSize: 38, lineHeight: 1.1 },
    gameTitle: { fontFamily: "'Pretendard', sans-serif", fontWeight: 800, fontSize: 26, letterSpacing: "-0.6px", color: C_DARK, margin: "6px 0 6px" },
    gameStage: { display: "flex", flexDirection: "column", alignItems: "stretch" },
    gameSvg: { width: "100%", height: "auto", display: "block", overflow: "visible", userSelect: "none", WebkitUserSelect: "none", WebkitTapHighlightColor: "transparent" },
    turnBanner: { display: "flex", alignItems: "center", justifyContent: "center", gap: 10, marginBottom: 14 },
    turnLabel: { fontSize: 13, fontWeight: 700, color: "#8A8FA3" },
    turnName: { fontSize: 20, fontWeight: 800, borderRadius: 4, padding: "4px 14px", letterSpacing: "-0.3px" },
    rouletteWrap: { maxWidth: 300, width: "100%", margin: "0 auto" },
    rouletteLabel: { fontFamily: "'Pretendard', sans-serif", fontSize: 15, fontWeight: 800 },
    ladderScroll: { overflowX: "auto", overflowY: "hidden", WebkitOverflowScrolling: "touch", overscrollBehaviorX: "contain", paddingBottom: 4 },
    ladderNames: { display: "grid", gap: 3, margin: "6px 0" },
    ladderName: { minWidth: 0, minHeight: 40, padding: "0 2px", border: "2px solid", borderRadius: 4, fontFamily: "inherit", fontSize: 12, fontWeight: 800, overflow: "hidden", whiteSpace: "nowrap", cursor: "pointer", transition: "background 0.15s, color 0.15s" },
    ladderResult: { minWidth: 0, minHeight: 44, display: "flex", flexDirection: "column", gap: 2, alignItems: "center", justifyContent: "center", borderRadius: 4, background: "#F6F8FB", border: "1px solid #E3E6EC", fontSize: 11.5, fontWeight: 700, color: C_DARK, overflow: "hidden", whiteSpace: "nowrap", textAlign: "center", padding: "0 2px" },
    ladderResultHidden: { color: "#B9BFCC" },
    ladderResultLabel: { lineHeight: 1.2 },
    ladderResultName: { maxWidth: "100%", overflow: "hidden", textOverflow: "clip", fontSize: 10.5, fontWeight: 800, lineHeight: 1.3, padding: "0 4px", borderRadius: 3 },
    ladderResultTarget: { background: C_RED, borderColor: C_RED, color: C_WHITE },
    bombWrap: { width: 190, maxWidth: "60%", margin: "0 auto" },
    bombSvg: { width: "100%", height: "auto", display: "block", overflow: "visible" },
    bombBoomText: { fontFamily: "'Pretendard', sans-serif", fontSize: 40, fontWeight: 900, fill: C_WHITE },

    // 미니게임 — 폰을 돌려가며 하는 게임 공용 (숫자 맞추기 · 10초 맞추기 · 동물 레이스)
    gameStageCenter: { display: "flex", flexDirection: "column", alignItems: "center" },
    gameCaption: { textAlign: "center", fontSize: 13, fontWeight: 700, color: "#8A8FA3", letterSpacing: "1px", margin: "0 0 12px" },
    gameMeta: { textAlign: "center", fontSize: 13, color: C_MUTED, margin: "0 0 14px" },
    privacyNote: { textAlign: "center", fontSize: 14, fontWeight: 700, color: "#7B5800", margin: "6px 0 20px", padding: "11px 16px", background: "#FFF8E1", border: "1px solid #FFE082", borderRadius: 4, lineHeight: 1.6 },
    privacyNoteSub: { fontSize: 12, fontWeight: 500, color: "#A07800" },
    rankList: { display: "flex", flexDirection: "column", gap: 6, marginBottom: 14 },
    rankRow: { display: "flex", alignItems: "center", gap: 10, padding: "8px 12px", background: "#F6F8FB", border: "1px solid #E3E6EC", borderRadius: 4 },
    rankRowHit: { background: "#FDF0EC", borderColor: "#F4C4B7" },
    rankNo: { width: 28, height: 28, flexShrink: 0, borderRadius: 4, display: "inline-flex", alignItems: "center", justifyContent: "center", fontSize: 13, fontWeight: 700 },
    rankName: { flex: 1, minWidth: 0, fontSize: 14, fontWeight: 700, color: C_DARK, overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap" },
    rankValue: { fontSize: 15, fontWeight: 800, color: C_DARK, fontVariantNumeric: "tabular-nums" },
    nameTag: { flexShrink: 0, fontSize: 12, fontWeight: 700, padding: "2px 8px", borderRadius: 10 },
    // 숫자 맞추기
    updownRange: { fontSize: 40, fontWeight: 900, color: C_DARK, letterSpacing: "-1px", fontVariantNumeric: "tabular-nums", textAlign: "center" },
    updownRangeHint: { margin: "2px 0 20px", fontSize: 11.5, color: C_MUTED, textAlign: "center" },
    updownInput: { textAlign: "center", fontSize: 32, fontWeight: 800, letterSpacing: "4px", marginBottom: 4, fontVariantNumeric: "tabular-nums" },
    feedbackEmoji: { fontSize: 72, lineHeight: 1, margin: "12px 0" },
    feedbackTitle: { fontSize: 24, fontWeight: 900, color: C_DARK, margin: "0 0 8px", letterSpacing: "-0.5px", textAlign: "center" },
    feedbackRange: { fontSize: 18, fontWeight: 800, color: C_DARK, margin: "0 0 8px", fontVariantNumeric: "tabular-nums" },
    // 10초 맞추기
    tensecDial: { width: 160, height: 160, borderRadius: "50%", border: "6px solid #E3E6EC", margin: "20px auto 8px", display: "flex", alignItems: "center", justifyContent: "center", background: "#F6F8FB", fontSize: 64 },
    tensecPeek: { margin: "20px auto", textAlign: "center", padding: "20px 28px", background: "#F6F8FB", border: "1.5px solid #E3E6EC", borderRadius: 4 },
    tensecPeekTime: { fontSize: 44, fontWeight: 900, color: C_DARK, fontVariantNumeric: "tabular-nums", letterSpacing: "-1px", margin: 0 },
    tensecPeekError: { fontSize: 16, fontWeight: 800, margin: "6px 0 0", fontVariantNumeric: "tabular-nums" },
    tensecElapsed: { fontSize: 13, color: C_MUTED, fontVariantNumeric: "tabular-nums" },
    tensecError: { minWidth: 60, fontSize: 12, fontWeight: 700, color: C_MUTED, textAlign: "right", fontVariantNumeric: "tabular-nums" },
    // 동물 레이스
    raceHead: { display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: 10 },
    raceStatus: { fontSize: 13, fontWeight: 700, color: "#8A8FA3", margin: 0 },
    raceTimer: { fontSize: 14, fontWeight: 800, color: C_MUTED, margin: 0, fontVariantNumeric: "tabular-nums" },
    raceTrack: { position: "relative", display: "flex", flexDirection: "column", boxSizing: "border-box", padding: "10px 8px 10px 4px", marginBottom: 12, background: "#F0FFF4", border: "1.5px solid #C8E6C9", borderRadius: 4 },
    raceFinishLine: { position: "absolute", right: 8, top: 6, bottom: 6, width: 3, background: "repeating-linear-gradient(180deg,#212121 0 5px,#fff 5px 10px)", opacity: 0.3, borderRadius: 1 },
    raceLane: { display: "flex", alignItems: "stretch", gap: 4, flex: "1 1 0" },
    raceLaneName: { minWidth: 34, alignSelf: "center", fontSize: 10, fontWeight: 700, color: C_DARK, textAlign: "right", overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap" },
    raceLaneTrack: { flex: 1, position: "relative", overflow: "hidden", marginRight: 12, background: "#E8F5E9", border: "1px solid #C8E6C9", borderRadius: 4, backgroundImage: "repeating-linear-gradient(90deg,transparent 0 20px,rgba(0,0,0,0.04) 20px 21px)" },
    raceRunner: { position: "absolute", top: "50%", transform: "translateY(-50%)", zIndex: 1, lineHeight: 0 },
    raceRankBadge: { position: "absolute", right: 2, top: "50%", transform: "translateY(-50%)", zIndex: 2, borderRadius: 8, padding: "1px 5px", fontSize: 10, fontWeight: 800 },
    raceFinishOrder: { fontSize: 11.5, color: C_MUTED, textAlign: "center", margin: "0 0 8px" },
    // 손가락 룰렛 (전체 화면 판)
    fingerCircle: { position: "absolute", width: 88, height: 88, borderRadius: "50%", pointerEvents: "none", transition: "transform 0.5s cubic-bezier(0.34,1.56,0.64,1), opacity 0.5s, border-color 0.3s" },
    fingerFooter: { position: "absolute", bottom: 100, left: 16, right: 16, textAlign: "center", pointerEvents: "none" },
    fingerCount: { color: C_WHITE, fontSize: 30, fontWeight: 900, margin: "0 0 4px", fontVariantNumeric: "tabular-nums" },
    fingerHint: { color: "rgba(255,255,255,0.55)", fontSize: 14, margin: 0 },
    fingerCountdown: { position: "absolute", inset: 0, display: "flex", flexDirection: "column", alignItems: "center", justifyContent: "center", pointerEvents: "none" },
    fingerCountdownNum: { fontSize: 120, fontWeight: 900, color: C_WHITE, textShadow: "0 4px 48px rgba(0,0,0,0.6)" },
    fingerResult: { position: "absolute", bottom: 60, left: 16, right: 16, textAlign: "center" },
    fingerResultText: { color: "#FFD700", fontSize: 26, fontWeight: 900, margin: "0 0 16px", textShadow: "0 2px 20px rgba(0,0,0,0.6)" },
    fingerBtnRow: { display: "flex", gap: 8, justifyContent: "center" },
    fingerBtn: { padding: "13px 22px", border: "none", borderRadius: 40, background: C_RED, color: C_WHITE, fontFamily: "inherit", fontSize: 16, fontWeight: 800, cursor: "pointer" },
    fingerBtnGhost: { background: "rgba(255,255,255,0.15)" },
    fingerSheet: { position: "absolute", left: 0, right: 0, bottom: 0, maxHeight: "70%", overflowY: "auto", background: C_WHITE, borderRadius: "16px 16px 0 0", padding: "18px 16px 28px" },
    fingerSheetTitle: { margin: "0 0 12px", fontSize: 16, fontWeight: 800, color: C_DARK, textAlign: "center" },
    fingerSheetGrid: { display: "grid", gridTemplateColumns: "1fr 1fr", gap: 8 },
    fingerSheetName: { padding: "12px 8px", border: "1px solid #E3E6EC", borderRadius: 4, background: "#F6F8FB", color: C_DARK, fontFamily: "inherit", fontSize: 15, fontWeight: 700, cursor: "pointer", overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap" },
    fingerSheetBack: { display: "block", margin: "14px auto 0", border: "none", background: "none", color: "#8A8FA3", fontFamily: "inherit", fontSize: 13, cursor: "pointer" },

    // 순서 정하기 · 순서 줄
    orderHead: { display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: 10 },
    shuffleBtn: { margin: 0, width: "auto", padding: "6px 14px", border: "1.5px dashed #C7CCD8", borderRadius: 4, background: "transparent", color: C_DIM, fontFamily: "inherit", fontSize: 12.5, fontWeight: 600, cursor: "pointer" },
    orderList: { listStyle: "none", margin: 0, padding: 0, display: "flex", flexDirection: "column", gap: 6 },
    orderRow: { display: "flex", alignItems: "center", gap: 10, padding: "6px 8px", background: "#F6F8FB", border: "1px solid #E3E6EC", borderRadius: 4 },
    orderNo: { width: 26, height: 26, flexShrink: 0, borderRadius: 4, display: "inline-flex", alignItems: "center", justifyContent: "center", fontFamily: "'Space Grotesk', 'Pretendard', sans-serif", fontSize: 13, fontWeight: 700 },
    orderName: { flex: 1, minWidth: 0, fontSize: 15, fontWeight: 700, color: C_DARK, overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap" },
    orderMoveBtn: { width: 36, height: 36, flexShrink: 0, border: "1.5px solid #DDE1E8", borderRadius: 4, background: C_WHITE, color: C_DARK, fontFamily: "inherit", fontSize: 16, lineHeight: 1, cursor: "pointer" },
    turnStrip: { display: "flex", flexWrap: "wrap", justifyContent: "center", alignItems: "center", rowGap: 6, marginBottom: 10 },
    turnChipWrap: { display: "inline-flex", alignItems: "center" },
    turnChip: { fontSize: 12, fontWeight: 700, color: "#8A8FA3", border: "1px solid #DDE1E8", borderRadius: 4, padding: "3px 7px", background: C_WHITE },
    turnArrow: { color: "#B9BFCC", fontSize: 14, margin: "0 4px" },

    // 3D 장면
    threeWrap: { position: "relative", width: "100%", borderRadius: 4, overflow: "hidden", background: `linear-gradient(180deg, #F6F8FB 0%, ${C_BG} 100%)` },
    threeCanvas: { position: "absolute", inset: 0 },
    dangerFlash: { position: "fixed", inset: 0, zIndex: 50, pointerEvents: "none", boxShadow: "inset 0 0 90px 30px rgba(215, 40, 47, 0.75)", animation: "dangerFlash 0.7s ease-out forwards" },
    zoomBtns: { position: "absolute", right: 8, bottom: 8, display: "flex", flexDirection: "column", gap: 6 },
    zoomBtn: { width: 38, height: 38, borderRadius: 4, border: "1px solid #DDE1E8", background: "rgba(255,255,255,0.92)", color: C_DARK, fontFamily: "inherit", fontSize: 20, fontWeight: 700, lineHeight: 1, cursor: "pointer", padding: 0, boxShadow: "0 1px 3px rgba(26,29,41,0.12)" },
    threeOverlay: { position: "absolute", inset: 0, display: "flex", alignItems: "center", justifyContent: "center", textAlign: "center", padding: 20, fontSize: 13, lineHeight: 1.6, color: "#8A8FA3", pointerEvents: "none" },

    // 폭탄 넘기기 — 폰을 받자마자 누르기 쉽게 크게
    // 터치 대결 — 화면 전체 판
    tapOverlay: { position: "fixed", inset: 0, zIndex: 200, display: "flex", flexDirection: "column", touchAction: "none", userSelect: "none", WebkitUserSelect: "none", WebkitTouchCallout: "none", WebkitTapHighlightColor: "transparent", overflow: "hidden" },
    tapCountBubble: { position: "absolute", left: "50%", top: "50%", transform: "translate(-50%, -50%)", width: 120, height: 120, borderRadius: "50%", background: "rgba(26,29,41,0.88)", color: C_WHITE, display: "flex", alignItems: "center", justifyContent: "center", pointerEvents: "none", boxShadow: "0 0 0 6px rgba(255,255,255,0.35)" },
    tapCountText: { fontFamily: "'Space Grotesk', 'Pretendard', sans-serif", fontSize: 54, fontWeight: 800, animation: "countPop 0.5s ease-out" },
    duelPreview: { display: "flex", flexDirection: "column", height: 200, borderRadius: 4, overflow: "hidden", marginBottom: 12 },
    duelPreviewHalf: { flex: 1, display: "flex", alignItems: "center", justifyContent: "center", fontSize: 20, fontWeight: 800 },
    duelHalf: { position: "relative", display: "flex", alignItems: "center", justifyContent: "center", overflow: "hidden", transition: "height 0.08s linear", cursor: "pointer" },
    duelLabel: { display: "flex", flexDirection: "column", alignItems: "center", gap: 2, pointerEvents: "none" },
    duelName: { fontSize: 20, fontWeight: 800 },
    duelTaps: { fontFamily: "'Space Grotesk', 'Pretendard', sans-serif", fontSize: 44, fontWeight: 800, lineHeight: 1.1, animation: "tapPulse 0.15s ease-out" },
    duelResult: { marginTop: 4, fontSize: 26, fontWeight: 900 },
    tapQuit: { position: "absolute", right: 10, width: 36, height: 36, borderRadius: "50%", border: "2px solid #FFFFFF", background: "rgba(26,29,41,0.75)", color: C_WHITE, fontSize: 16, fontWeight: 700, cursor: "pointer", zIndex: 2 },
    relayPad: { flex: 1, display: "flex", flexDirection: "column", alignItems: "center", justifyContent: "center", gap: 10, cursor: "pointer" },
    relayTaps: { fontFamily: "'Space Grotesk', 'Pretendard', sans-serif", fontSize: 96, fontWeight: 800, lineHeight: 1, animation: "tapPulse 0.15s ease-out", pointerEvents: "none" },
    relayTimeTrack: { width: "70%", height: 10, borderRadius: 5, background: "rgba(0,0,0,0.18)", overflow: "hidden", pointerEvents: "none" },
    relayTimeBar: { height: "100%", borderRadius: 5 },
    relayHint: { fontSize: 18, fontWeight: 700, pointerEvents: "none" },
    relayBoard: { listStyle: "none", margin: "0 0 4px", padding: 0, display: "flex", flexDirection: "column", gap: 6 },
    relayRow: { display: "flex", alignItems: "center", gap: 10, padding: "8px 10px", border: "1px solid #E3E6EC", borderRadius: 4, background: C_WHITE },
    relayRowNow: { borderColor: C_DARK, boxShadow: `inset 3px 0 0 ${C_RED}` },
    relayScore: { marginLeft: "auto", fontFamily: "'Space Grotesk', 'Pretendard', sans-serif", fontWeight: 700, color: C_DARK },
    passBtn: { marginTop: 14, width: "100%", minHeight: 120, border: "none", borderRadius: 4, background: C_RED, color: C_WHITE, fontFamily: "inherit", display: "flex", flexDirection: "column", alignItems: "center", justifyContent: "center", gap: 4, boxShadow: "3px 5px 0 #B8391F", cursor: "pointer", transition: "transform 0.12s, box-shadow 0.12s, opacity 0.15s" },
    passBtnMain: { fontSize: 30, fontWeight: 900, letterSpacing: "-0.5px" },
    passBtnSub: { fontSize: 16, fontWeight: 700, opacity: 0.9 },

    // 미니게임 — 결과
    loserBlock: { textAlign: "center", padding: "10px 0 16px" },
    loserEmoji: { fontSize: 44, lineHeight: 1.1 },
    loserName: { fontSize: 34, fontWeight: 900, letterSpacing: "-1px", color: C_RED, marginTop: 6 },
    loserNameMany: { fontSize: 26, letterSpacing: "-0.5px", lineHeight: 1.3 },
    loserText: { fontSize: 14, color: C_DIM, marginTop: 4 },
    loserPlayers: { fontSize: 12, color: C_MUTED, borderTop: "1px solid #F0F2F6", paddingTop: 10, textAlign: "center", lineHeight: 1.6 },
    linkBtn: { display: "flex", alignItems: "center", justifyContent: "center", textDecoration: "none" },
    adSlot: { margin: "16px auto 0", width: "100%", minHeight: 60 },
    adSlotPreview: { display: "flex", alignItems: "center", justifyContent: "center", border: "1px dashed #B9BFCC", borderRadius: 4, background: "#F6F8FB", color: C_MUTED, fontSize: 11, fontWeight: 600 },

    tabBar: { position: "fixed", left: 0, right: 0, bottom: 0, zIndex: 50, background: "rgba(255,255,255,0.97)", borderTop: "1px solid #E3E6EC", paddingBottom: "env(safe-area-inset-bottom)", boxShadow: "0 -6px 18px rgba(26,29,41,0.05)" },
    tabInner: { maxWidth: 440, margin: "0 auto", display: "flex" },
    tabItem: { flex: 1, height: TAB_BAR_HEIGHT, display: "flex", flexDirection: "column", alignItems: "center", justifyContent: "center", gap: 3, fontSize: 11.5, fontWeight: 600, color: C_MUTED, textDecoration: "none", transition: "color 0.15s", WebkitTapHighlightColor: "transparent" },
    tabItemActive: { color: C_DARK, fontWeight: 800, boxShadow: `inset 0 2px 0 ${C_RED}` },
    tabIcon: { fontSize: 22 },
    tabIconWrap: { position: "relative", display: "flex" },
    newBadge: { position: "absolute", top: -6, left: "calc(100% - 6px)", padding: "1px 4px", borderRadius: 6, background: C_RED, color: C_WHITE, fontSize: 9, fontWeight: 800, lineHeight: 1.3, letterSpacing: 0.2, boxShadow: "0 0 0 2px #FFFFFF" },

    previewOverlay: { position: "fixed", inset: 0, zIndex: 1000, background: "rgba(20,22,30,0.82)", display: "flex", flexDirection: "column", alignItems: "center", justifyContent: "center", padding: 20, overflowY: "auto" },
    previewBox: { width: "100%", maxWidth: 380, display: "flex", flexDirection: "column", alignItems: "center", gap: 12 },
    previewHint: { margin: 0, color: C_WHITE, fontSize: 13.5, lineHeight: 1.6, textAlign: "center" },
    previewImg: { width: "100%", height: "auto", borderRadius: 6, boxShadow: "0 12px 32px rgba(0,0,0,0.4)", background: C_WHITE, WebkitTouchCallout: "default" },
    previewBtnRow: { display: "flex", gap: 8, width: "100%" },
    previewShareBtn: { flex: 1, padding: "12px 0", border: "none", borderRadius: 4, background: C_GREEN, color: C_WHITE, fontFamily: "inherit", fontSize: 14, fontWeight: 700, cursor: "pointer" },
    previewCloseBtn: { flex: 1, padding: "12px 0", border: "1px solid rgba(255,255,255,0.5)", borderRadius: 4, background: "transparent", color: C_WHITE, fontFamily: "inherit", fontSize: 14, fontWeight: 700, cursor: "pointer" },
};
